---
title: Derrick Wells – Independent Product Designer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
logo: 
description: Passionate designer curating designs for new startups  and  founders  and
  crafts  beautiful user interfaces with love.
baseurl: "/derrick"
url: ''
author:
  name: Derrick Wells
  image: "/assets/img/01.jpg"
  job: Independent Product Designer
  bio: Passionate designer curating designs for new startups  and  founders  and crafts  beautiful
    user interfaces with love.
  email: forexample@website.com
contact:
- name: Twitter
  link: https://twitter.com/
- name: Facebook
  link: https://facebook.com/
- name: Instagram
  link: https://instagram.com/
disqus-identifier: mr-brown
google-analytics: 
markdown: kramdown
permalink: pretty
plugins:
- jekyll-sitemap
- jekyll/tagging
include:
- _pages
tag_page_dir: tag
tag_page_layout: tag-page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- vendor
